/**
 * Official Homestay Room Catalog for YOJQI Direct Booking Channel
 * 
 * Maps directly to Hostex (百居易) OpenAPI v3 & House Types & Physical Properties
 * 
 * Strict Single Source of Truth architecture:
 * - Differentiates between '房型' (Pooled Room Types with shared availability across SKUs)
 *   and '房间' (Dedicated Individual Rooms with 1:1 physical property assignment)
 * - Adheres strictly to the user's optimized bilingual naming table
 * - 1.8m bed -> King Bed / 特大双人床 (1.8m)
 * - 1.5m bed -> Double Bed / 大双人床 (1.5m)
 * - Floor-to-ceiling windows -> Floor-to-Ceiling Windows / 全景落地窗
 * - Balcony -> Private Balcony / 大阳台 / 私享阳台
 * - Multi-bedroom apartments -> Apartment
 */

export type RetreatDisplayType = 'room_type' | 'individual_room';

export interface RetreatRoomType {
  room_key: string;
  slug: string;
  display_type: RetreatDisplayType; // '房型' or '房间'
  pms_sku?: string; // Physical SKU name in Hostex (e.g. 'BH东B7-2-8雪柳花2室')
  house_type_id: number;
  listing_id: string; // Primary Booking.com listing used for calendar & live pricing
  property_ids: number[]; // Physical property IDs in Hostex
  default_property_id: number;
  
  // Bilingual Marketing & Names
  nameZh: string;
  nameEn: string;
  subtitleZh: string;
  subtitleEn: string;
  badgeZh: string;
  badgeEn: string;
  
  // Specs
  area: string;
  floorZh: string;
  floorEn: string;
  capacity: number;
  bedInfoZh: string;
  bedInfoEn: string;
  viewZh: string;
  viewEn: string;
  
  // Pricing & Value
  basePrice: number; // RMS baseline anchor price
  minFloorPrice: number; // RMS hard floor price protection
  
  // Visuals
  coverImage: string;
  gallery: string[];
  
  // Amenities & Highlights
  tagsZh: string[];
  tagsEn: string[];
  amenitiesZh: string[];
  amenitiesEn: string[];
  droneVantageZh: string;
  droneVantageEn: string;
  
  // Direct Booking Perks
  directPerksZh: string[];
  directPerksEn: string[];
  
  // Policies
  cancellationPolicyZh: string;
  cancellationPolicyEn: string;
  checkInTime: string;
  checkOutTime: string;
}

export const RETREAT_ROOM_CATALOG: RetreatRoomType[] = [
  // ==========================================
  // 【一、房型池产品 (展示方式 = 房型 · 共7款)】
  // ==========================================
  {
    room_key: 'floor_window_king',
    slug: 'high-floor-river-view-king-floor-to-ceiling-windows',
    display_type: 'room_type',
    house_type_id: 71446,
    listing_id: '1714162802-69081086',
    property_ids: [12316815, 12777272, 11587530, 12512774, 12724674, 12752494],
    default_property_id: 11587530,
    nameZh: '全景落地窗·高空江景大床房',
    nameEn: 'High-Floor River View King Room with Floor-to-Ceiling Windows',
    subtitleZh: '整面通顶巨幕落地窗 · 临窗深泡浴缸 · 沉浸式赛博山城夜色',
    subtitleEn: 'Full-wall panoramic glass, soaking tub by the window, immersive city skyline',
    badgeZh: '房型 · 巨幕落地窗',
    badgeEn: 'Room Type · Panoramic Windows',
    area: '45 ㎡',
    floorZh: '高空 10-30 层',
    floorEn: 'Floors 10-30',
    capacity: 2,
    bedInfoZh: '1张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '1 King Bed (1.8m × 2.0m)',
    viewZh: '洪崖洞吊脚楼顶 / 千厮门大桥灯光 / 城市天际线',
    viewEn: 'Hongyadong Stilt Roofs, Qiansimen Bridge Lights, Cyberpunk Skyline',
    basePrice: 628,
    minFloorPrice: 380,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['巨幕落地窗', '观景深泡池', '千厮门大桥', '胶囊咖啡', '香氛体验'],
    tagsEn: ['Panoramic Glass', 'Soaking Tub', 'Bridge View', 'Espresso Machine', 'Botanical Scent'],
    amenitiesZh: [
      '临窗定制景观泡池与天然植物沐浴草本',
      '通顶全幅隔音落地玻璃，饱览山城立体夜幕',
      '高织精梳棉奢华床品，静音电动遮光帘',
      '胶囊咖啡机与东方原叶茶礼盒',
      '智能马桶与戴森高速吹风机',
    ],
    amenitiesEn: [
      'Window-side soaking tub with herbal bath rituals',
      'Ceiling-high acoustic glass wall over illuminated bridges',
      'High-thread combed cotton bedding and electric blackout curtains',
      'Capsule coffee machine and loose-leaf tea selection',
      'Smart bidet toilet and high-velocity hair dryer',
    ],
    droneVantageZh: '大开面落地窗视野，傍晚坐在浴缸或茶榻边即可尽揽千厮门大桥灯海与天际飞星。',
    droneVantageEn: 'Expansive glass view; enjoy the evening bridge light sea and drone formations right from your sofa.',
    directPerksZh: ['官网直订立享 95 折', '免费泡汤草本浴盐包', '免费行李寄存', '优先选房权益'],
    directPerksEn: ['Official 5% Direct Discount', 'Herbal Bath Soak Kit', 'Free Luggage Storage', 'Preferred Room Assignment'],
    cancellationPolicyZh: '入住前 48 小时可免费取消；48 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 48 hours prior to check-in. Cancellations within 48 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'twin_view_a',
    slug: 'high-floor-river-view-suite-2-king-beds',
    display_type: 'room_type',
    house_type_id: 71445,
    listing_id: '1714162803-69081086',
    property_ids: [12316814, 11587529, 12724675],
    default_property_id: 11587529,
    nameZh: '高空江景·双大床套房',
    nameEn: 'High-Floor River View Suite with 2 King Beds',
    subtitleZh: '一室一厅双大床规制 · 闺蜜、亲友与商务从容出行 · 窗前品茗远眺水色',
    subtitleEn: 'High-floor suite with 2 king beds and 1 living room, serene bridge and river vistas',
    badgeZh: '房型 · 双大床套房',
    badgeEn: 'Room Type · 2 King Beds',
    area: '52 ㎡',
    floorZh: '高空 10-30 层',
    floorEn: 'Floors 10-30',
    capacity: 4,
    bedInfoZh: '2张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '2 King Beds (1.8m × 2.0m)',
    viewZh: '千厮门大桥 / 嘉陵江水色 / 城市繁华天际',
    viewEn: 'Qiansimen Bridge, Jialing River, Skyline',
    basePrice: 688,
    minFloorPrice: 420,
    coverImage: '/images/retreats/baihong-room-02.jpg',
    gallery: [
      '/images/retreats/baihong-room-02.jpg',
      '/images/retreats/baihong-room-01.jpg',
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    ],
    tagsZh: ['双大床套房', '一室一厅', '干湿分离', '独立茶几', '隔音静谧'],
    tagsEn: ['2 King Beds', '1 Living Room', 'Divided Bath', 'Tea Corner', 'Quiet Glazing'],
    amenitiesZh: [
      '两张独立 1.8m 护脊硬棕乳胶大床',
      '独立观景品茗休闲客厅座席',
      '干湿分离卫浴空间与高压恒温淋浴',
      '四人洗漱备品与纯棉厚款浴袍',
    ],
    amenitiesEn: [
      'Two ergonomic 1.8m king beds with supportive mattresses',
      'Scenic tea lounge living room for conversation',
      'Split bathroom with thermostatic rainfall shower',
      'Plush bathrobes and premium organic amenities',
    ],
    droneVantageZh: '窗前平视两江水面与桥头车流，是与好友或家人静度周末的理想居所。',
    droneVantageEn: 'Clear window perspective facing the water convergence, ideal for friends and family traveling together.',
    directPerksZh: ['官网直订立享 95 折', '专属迎宾冷泡茶礼', '免费寄存行李'],
    directPerksEn: ['Official 5% Direct Discount', 'Complimentary Cold Brew Tea Pair', 'Free Luggage Storage'],
    cancellationPolicyZh: '入住前 48 小时可免费取消；48 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 48 hours prior to check-in. Cancellations within 48 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'twin_view_b',
    slug: 'river-view-family-suite-2-king-beds',
    display_type: 'room_type',
    house_type_id: 221229,
    listing_id: '1714162804-69081086',
    property_ids: [12777273, 12512776, 12752495],
    default_property_id: 12512776,
    nameZh: '江景双大床家庭套房',
    nameEn: 'River View Family Suite with 2 King Beds',
    subtitleZh: '开阔双大床大空间 · 一室一厅 · 宽幅江景视野 · 宁静素雅木质格调',
    subtitleEn: 'Spacious 1-bedroom family suite with 2 king beds, expansive riverfront panorama',
    badgeZh: '房型 · 双大床家庭套房',
    badgeEn: 'Room Type · 2 King Beds Family Suite',
    area: '55 ㎡',
    floorZh: '高空 16-26 层',
    floorEn: 'Floors 16-26',
    capacity: 4,
    bedInfoZh: '2张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '2 King Beds (1.8m × 2.0m)',
    viewZh: '两江宽阔水域 / 对岸江北嘴现代金融城灯火',
    viewEn: 'Yangtze Expanse & Jiangbeizui CBD Skyline',
    basePrice: 718,
    minFloorPrice: 450,
    coverImage: '/images/retreats/baihong-room-03.jpg',
    gallery: [
      '/images/retreats/baihong-room-03.jpg',
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    ],
    tagsZh: ['全景视野', '双大床家庭', '高织床品', '原木美学', '静音空调'],
    tagsEn: ['Panoramic Sight', '2 King Beds Family', 'High-Thread Linens', 'Wooden Decor', 'Silent AC'],
    amenitiesZh: [
      '高空超宽画幅观江落地窗与一室一厅格局',
      '高品质两张 1.8m 特大双人床与抗菌鹅绒被芯',
      '原木工夫茶台与专属安神香氛',
    ],
    amenitiesEn: [
      'High-altitude wide-angle riverfront glazing with 1 living room layout',
      'Two 1.8m king beds with antibacterial goose down duvets',
      'Solid wooden tea table with signature calming incense',
    ],
    droneVantageZh: '极高视点平视夜间空域，尽览对岸大剧院与江北嘴灯光大秀。',
    droneVantageEn: 'High vantage point overlooking river aerials and the Grand Theatre light choreography.',
    directPerksZh: ['官网直订立享 95 折', '专属东方欢迎茶礼', '免费行李寄存'],
    directPerksEn: ['Official 5% Direct Discount', 'Welcome Tea Set', 'Free Luggage Storage'],
    cancellationPolicyZh: '入住前 48 小时可免费取消；48 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 48 hours prior to check-in. Cancellations within 48 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'balcony_king_a',
    slug: 'river-view-king-suite-with-private-balcony',
    display_type: 'room_type',
    house_type_id: 83516,
    listing_id: '1714162801-69081086',
    property_ids: [11587528, 12724673, 11503730],
    default_property_id: 11587528,
    nameZh: '私享阳台·江景大床套房',
    nameEn: 'River View King Suite with Private Balcony',
    subtitleZh: '高空私享观景阳台 · 独立套房格局 · 临窗品茗远眺两江流光',
    subtitleEn: 'High-altitude suite with private balcony overlooking Yangtze & Jialing rivers with tea station',
    badgeZh: '房型 · 私享阳台',
    badgeEn: 'Room Type · Private Balcony',
    area: '48 ㎡',
    floorZh: '高空 7-30 层',
    floorEn: 'Floors 7-30',
    capacity: 2,
    bedInfoZh: '1张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '1 King Bed (1.8m × 2.0m)',
    viewZh: '两江汇聚江景 / 洪崖洞木质灯火 / 城市夜幕',
    viewEn: 'Two Rivers Confluence, Hongyadong Lights, Sunset Horizon',
    basePrice: 668,
    minFloorPrice: 400,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      '/images/retreats/baihong-room-01.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['私享独立阳台', '两江汇流', '静音茶席', '智能温控', '双层隔音玻璃'],
    tagsEn: ['Private Balcony', 'Riverfront View', 'Tea Station', 'Smart Climate', 'Acoustic Glazing'],
    amenitiesZh: [
      '高空私享观景阳台与实木茶座',
      '天然水洗亚麻高织床品与零压乳胶枕',
      '工夫茶席配备精选陈年普洱与甘冽山泉',
      '干湿分离独立卫浴、热带雨林花洒',
    ],
    amenitiesEn: [
      'Private high-altitude riverfront terrace with tea furniture',
      'Premium washed linen bedding and memory foam pillows',
      'Full Kung Fu tea set with aged Pu-erh and bottled spring water',
      'Designer bathroom with walk-in rainforest shower',
    ],
    droneVantageZh: '正对朝天门与两江交汇天幕空域，端坐阳台茶席即可免挤平视无人机编队起降。',
    droneVantageEn: 'Direct visual line to the Chaotianmen aerial formation zone; relax on your private terrace away from street crowds.',
    directPerksZh: ['官网直订立享 95 折', '专属东方迎宾欢迎茶礼', '免费提早入住 (视房态)'],
    directPerksEn: ['Official 5% Direct Discount', 'Complimentary Welcome Tea Gift', 'Priority Early Check-in (subject to availability)'],
    cancellationPolicyZh: '入住前 48 小时可免费取消；48 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 48 hours prior to check-in. Cancellations within 48 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'balcony_king_b',
    slug: 'river-view-king-suite-balcony-floor-to-ceiling-windows',
    display_type: 'room_type',
    house_type_id: 221230,
    listing_id: '1714162801-69081086',
    property_ids: [12777271, 12512775, 12752493],
    default_property_id: 12512775,
    nameZh: '私享阳台·全景落地窗江景大床套房',
    nameEn: 'River View King Suite with Private Balcony & Floor-to-Ceiling Windows',
    subtitleZh: '高空私享超大观景阳台与通顶落地窗双重景致 · 配备大床与沙发床',
    subtitleEn: 'Private balcony & floor-to-ceiling windows overlooking two rivers; equipped with 1 king bed and sofa bed',
    badgeZh: '房型 · 阳台+落地窗',
    badgeEn: 'Room Type · Balcony & Glass Wall',
    area: '52 ㎡',
    floorZh: '高空 16-26 层',
    floorEn: 'Floors 16-26',
    capacity: 3,
    bedInfoZh: '1张特大双人床 (1.8m) + 1张沙发床',
    bedInfoEn: '1 King Bed (1.8m) + 1 Sofa Bed',
    viewZh: '两江交汇全江景 / 洪崖洞木质灯火 / 绝美日落晚霞',
    viewEn: 'Two Rivers Confluence, Hongyadong Lights, Sunset Horizon',
    basePrice: 698,
    minFloorPrice: 430,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      '/images/retreats/baihong-room-01.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['私享阳台', '全景落地窗', '沙发床加位', '智能温控', '双层隔音'],
    tagsEn: ['Private Balcony', 'Floor-to-Ceiling Glass', 'Sofa Bed', 'Smart Climate', 'Acoustic Glazing'],
    amenitiesZh: [
      '超大高空私享观景阳台与通顶全画幅落地窗',
      '1.8m特大双人床与加厚舒适多功能沙发床',
      '工夫茶席配备精选陈年普洱与甘冽山泉',
      '干湿分离独立卫浴、热带雨林花洒',
    ],
    amenitiesEn: [
      'High-altitude riverfront balcony combined with full glass wall',
      '1.8m King bed and plush multifunctional sofa bed',
      'Full Kung Fu tea set with premium tea selection',
      'Designer bathroom with walk-in rainforest shower',
    ],
    droneVantageZh: '正对朝天门与两江交汇天幕空域，端坐阳台茶席即可免挤平视千架无人机编队起降。',
    droneVantageEn: 'Direct visual line to the Chaotianmen aerial formation zone; relax on your private terrace away from street crowds.',
    directPerksZh: ['官网直订立享 95 折', '专属东方迎宾欢迎茶礼', '免费提早入住 (视房态)'],
    directPerksEn: ['Official 5% Direct Discount', 'Complimentary Welcome Tea Gift', 'Priority Early Check-in (subject to availability)'],
    cancellationPolicyZh: '入住前 48 小时可免费取消；48 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 48 hours prior to check-in. Cancellations within 48 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'suite_4bed_family',
    slug: 'hongyadong-panoramic-river-view-4-bedroom-apartment-projector',
    display_type: 'room_type',
    house_type_id: 219896,
    listing_id: '1714162806-68618636',
    property_ids: [12497196, 12733837],
    default_property_id: 12497196,
    nameZh: '洪崖洞一线江景·4卧室整套·投影·全景落地窗',
    nameEn: 'Hongyadong Panoramic River View 4-Bedroom Apartment with Projector',
    subtitleZh: '四室0厅3卫四床整套格局 · 巨幕高清投影 · 巨幅落地窗一线瞰江 · 多家庭品质同居',
    subtitleEn: 'Entire 4-bedroom apartment with 4 king beds, 3 bathrooms, panoramic windows, and HD projector',
    badgeZh: '房型 · 4室整套·投影·落地窗',
    badgeEn: 'Room Type · 4-Bed Apartment',
    area: '155 ㎡',
    floorZh: '高空 10-30 层',
    floorEn: 'Floors 10-30',
    capacity: 8,
    bedInfoZh: '4张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '4 King Beds (1.8m × 2.0m)',
    viewZh: '一线长江与嘉陵江景 / 洪崖洞商圈 / 城市高空全景',
    viewEn: 'Front-Row River Views, Hongyadong Proximity, Skyline',
    basePrice: 1688,
    minFloorPrice: 980,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['4室整套包栋', '4张大床', '3个独立卫浴', '巨幕影院投影', '全景落地窗'],
    tagsEn: ['Entire 4-Bed Flat', '4 King Beds', '3 Bathrooms', 'HD Projector', 'Floor-to-Ceiling Glass'],
    amenitiesZh: [
      '整套独享 4 卧 3 卫格局，4 张 1.8m 特大双人床',
      '超大巨幕高清投影仪，家庭影院视听体验',
      '通顶落地玻璃窗，一线开阔水色江景',
      '全自动洗烘一体机与多家庭备品',
    ],
    amenitiesEn: [
      'Entire apartment layout with 4 private bedrooms, 3 full bathrooms, and 4 king beds',
      'High-definition cinema projector for family entertainment',
      'Expansive ceiling-high glass windows facing the river',
      'Washer-dryer and family travel amenities',
    ],
    droneVantageZh: '近邻洪崖洞与解放碑核心，高空平视两江夜景与天际航线。',
    droneVantageEn: 'Close proximity to Hongyadong, high-altitude vantage point for city aerials.',
    directPerksZh: ['官网直订立享 95 折', '全家出行专属茶礼', '免费行李寄存', 'VIP专属管家'],
    directPerksEn: ['Official 5% Direct Discount', 'Family Tea Gift', 'Free Luggage Storage', 'VIP Butler'],
    cancellationPolicyZh: '入住前 72 小时可免费取消；72 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 72 hours prior to check-in. Cancellations within 72 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'suite_4bed_balcony',
    slug: 'river-view-4-bedroom-apartment-large-balcony-projector',
    display_type: 'room_type',
    house_type_id: 191968,
    listing_id: '1714162805-68618636',
    property_ids: [12777274, 12491346, 12752496],
    default_property_id: 12491346,
    nameZh: '大阳台·江景4卧室整套·百寸投影',
    nameEn: 'River View 4-Bedroom Apartment with Large Balcony & 100-inch Projector',
    subtitleZh: '四室0厅3卫四床整套格局 · 专属超大观景阳台 · 百寸巨幕投影 · 亲友包栋尊享',
    subtitleEn: 'Entire 4-bedroom apartment with 4 king beds, large private balcony, and 100-inch projector',
    badgeZh: '房型 · 4室大阳台·百寸投影',
    badgeEn: 'Room Type · 4-Bed Balcony Apartment',
    area: '168 ㎡',
    floorZh: '高空 16-26 层',
    floorEn: 'Floors 16-26',
    capacity: 8,
    bedInfoZh: '4张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '4 King Beds (1.8m × 2.0m)',
    viewZh: '360°环幕两江交汇 / 洪崖洞全景 / 渝中半岛灯海',
    viewEn: '360° Two Rivers Panorama, Hongyadong Roofs, Peninsula Lights',
    basePrice: 1888,
    minFloorPrice: 1100,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['独门独户整套', '4室4大床', '全景大阳台', '百寸巨幕投影', '3独立卫浴'],
    tagsEn: ['Entire Penthouse', '4 King Beds', 'Grand Balcony', '100-inch Projector', '3 Bathrooms'],
    amenitiesZh: [
      '整套 168 ㎡ 独门私密格局，4 间独立卧室均配备 1.8m 特大双人床',
      '超大高空私享揽江阳台，可供全家饮茶聚会观赏夜景',
      '百寸高清巨幕投影，三独立卫生间，全自动洗衣烘干机',
      '工夫茶台与全套茶器，厨房配备冷热饮水与餐具',
    ],
    amenitiesEn: [
      'Entire 168 ㎡ layout with 4 private bedrooms, all with 1.8m king beds',
      'Oversized private high-altitude terrace for whole-family gatherings',
      '100-inch HD cinema projector, 3 full bathrooms, washer & dryer',
      'Kung Fu tea station and pantry equipped with tableware',
    ],
    droneVantageZh: '无人机航线正前方的私人空中头等舱，全家人围坐大阳台无遮挡欢聚观礼。',
    droneVantageEn: 'Skybox front-row vantage point right before drone aerial zones; watch without jostling with crowds.',
    directPerksZh: ['官网直订立享 95 折', '尊享全家欢迎茶礼', '免费提前行李寄存', 'VIP 专线管家全程服务'],
    directPerksEn: ['Official 5% Direct Discount', 'Family Welcome Tea Selection', 'Early Luggage Concierge', 'VIP Butler Channel'],
    cancellationPolicyZh: '入住前 72 小时可免费取消；72 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 72 hours prior to check-in. Cancellations within 72 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },

  // ==========================================
  // 【二、独立房间产品 (展示方式 = 房间 · 共9款)】
  // ==========================================
  {
    room_key: 'room_b7_2_8_xueliuhua',
    slug: 'hongyadong-high-floor-river-view-2-bedroom-suite',
    display_type: 'individual_room',
    pms_sku: 'BH东B7-2-8雪柳花2室',
    house_type_id: 21553,
    listing_id: '642948137-47013688',
    property_ids: [11503729],
    default_property_id: 11503729,
    nameZh: '洪崖洞高空江景·2卧室大床套房',
    nameEn: 'Hongyadong High-Floor River View 2-Bedroom Suite',
    subtitleZh: '2个独立卧室1客厅1卫生间 · 纯正高空两卧套房 · 舒适静谧出行',
    subtitleEn: 'High-floor 2-bedroom suite with living room and bathroom, peaceful river views for families or friends',
    badgeZh: '独立房间 · 2卧室大床套房',
    badgeEn: 'Dedicated Suite · 2-Bedroom',
    area: '82 ㎡',
    floorZh: '高空 7 层',
    floorEn: 'Floor 7',
    capacity: 4,
    bedInfoZh: '2张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '2 King Beds (1.8m × 2.0m)',
    viewZh: '高空两江江景与城市绿意交融',
    viewEn: 'High-Floor River Vista and City Horizon',
    basePrice: 888,
    minFloorPrice: 520,
    coverImage: '/images/retreats/baihong-room-03.jpg',
    gallery: [
      '/images/retreats/baihong-room-03.jpg',
      '/images/retreats/baihong-room-01.jpg',
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    ],
    tagsZh: ['独立房间', '两卧一厅', '2张特大床', '舒适静谧', '家庭优选'],
    tagsEn: ['Dedicated Unit', '2 Beds 1 Living', '2 King Beds', 'Peaceful Stay', 'Family Suite'],
    amenitiesZh: [
      '独立 2 卧 1 厅 1 卫规制，两间卧室互不干扰',
      '两张 1.8m 护脊硬棕乳胶大床',
      '独立观景客厅、工夫茶台与洗衣机',
    ],
    amenitiesEn: [
      '2 private bedrooms with dedicated central living lounge & 1 bathroom',
      'Two 1.8m King beds with ergonomic support',
      'Scenic lounge with Kung Fu tea station and washer',
    ],
    droneVantageZh: '舒适静卧观赏两江流光，漫步数分钟即达洪崖洞与滨江步道。',
    droneVantageEn: 'Tranquil perspective over the water, short walk to Hongyadong and river promenade.',
    directPerksZh: ['官网直订立享 95 折', '专属迎宾茶礼', '免费行李寄存'],
    directPerksEn: ['Official 5% Direct Discount', 'Welcome Tea Set', 'Free Luggage Storage'],
    cancellationPolicyZh: '入住前 48 小时可免费取消；48 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 48 hours prior to check-in. Cancellations within 48 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'room_b19_2_yueshuxing',
    slug: 'hongyadong-river-view-4-bedroom-suite-mahjong',
    display_type: 'individual_room',
    pms_sku: 'BH东B19-2月疏影',
    house_type_id: 31727,
    listing_id: '1714162805-68618636',
    property_ids: [11285380],
    default_property_id: 11285380,
    nameZh: '洪崖洞江景·4卧室套房·投影·麻将桌',
    nameEn: 'Hongyadong River View 4-Bedroom Suite with Projector & Mahjong Table',
    subtitleZh: '4个独立卧室1客厅2卫生间 · 3张1.8米大床+1张1.5米大床 · 巨幕投影与自动麻将机',
    subtitleEn: '4 private bedrooms with 3 King Beds + 1 Double Bed, home projector, and mahjong table',
    badgeZh: '独立房间 · 4卧+投影+机麻',
    badgeEn: 'Dedicated Suite · Mahjong & Cinema',
    area: '148 ㎡',
    floorZh: '高空 19 层',
    floorEn: 'Floor 19',
    capacity: 8,
    bedInfoZh: '3张特大双人床 (1.8m) + 1张大双人床 (1.5m)',
    bedInfoEn: '3 King Beds (1.8m) + 1 Double Bed (1.5m)',
    viewZh: '洪崖洞璀璨江景 / 两江汇水色 / 城市繁华',
    viewEn: 'Hongyadong River Lights, Two Rivers Expanse, Skyline',
    basePrice: 1588,
    minFloorPrice: 920,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['独立房间', '4独立卧室', '自动麻将机', '巨幕影音投影', '双独立卫生间'],
    tagsEn: ['Dedicated Unit', '4 Bedrooms', 'Mahjong Table', 'Cinema Projector', '2 Bathrooms'],
    amenitiesZh: [
      '4 间独立卧室配备 3 张 1.8m 特大双人床与 1 张 1.5m 大双人床',
      '全自动麻将桌，亲友聚会娱乐首选',
      '客厅配备百寸巨幕影音投影仪与工夫茶席',
      '双独立干湿分离卫生间与洗烘设备',
    ],
    amenitiesEn: [
      '4 private bedrooms with 3 King Beds (1.8m) and 1 Double Bed (1.5m)',
      'Automatic mahjong table for family gatherings',
      'Spacious living salon with cinema projector & Kung Fu tea table',
      'Two full bathrooms and washer-dryer',
    ],
    droneVantageZh: '高空 19 层直面江面空域，傍晚尽览千厮门大桥车水马龙与无人机编队大秀。',
    droneVantageEn: '19th floor aerial line of sight directly over the water confluence and nightly drone shows.',
    directPerksZh: ['官网直订立享 95 折', '聚会欢迎零食与茶礼', '免费提前行李寄存'],
    directPerksEn: ['Official 5% Direct Discount', 'Gathering Tea & Snack Basket', 'Free Luggage Storage'],
    cancellationPolicyZh: '入住前 72 小时可免费取消；72 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 72 hours prior to check-in. Cancellations within 72 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'room_b22_01_qingying',
    slug: 'river-view-4-bedroom-balcony-mahjong-qingying',
    display_type: 'individual_room',
    pms_sku: 'BH东B22-01清影',
    house_type_id: 31727,
    listing_id: '1714162805-68618636',
    property_ids: [12381299],
    default_property_id: 12381299,
    nameZh: '江景阳台·4卧室大床套房·麻将桌 (清影)',
    nameEn: 'River View 4-Bedroom Suite with Private Balcony & Mahjong Table (Qing Ying)',
    subtitleZh: '4个独立卧室1客厅2卫生间 · 4张1.8米大床 · 私享观景阳台与自动麻将机',
    subtitleEn: '4 private bedrooms, 1 living room, 2 bathrooms, 4 king beds, private balcony, and mahjong table',
    badgeZh: '独立房间 · 清影·22层',
    badgeEn: 'Dedicated Room · Qing Ying',
    area: '152 ㎡',
    floorZh: '高空 22 层',
    floorEn: 'Floor 22',
    capacity: 8,
    bedInfoZh: '4张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '4 King Beds (1.8m × 2.0m)',
    viewZh: '两江交汇全江景 / 高空私享观景大阳台',
    viewEn: 'Two Rivers Confluence, High-Floor Terrace',
    basePrice: 1688,
    minFloorPrice: 980,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['独立房间', '4张大床', '私享大阳台', '自动麻将桌', '高空22层'],
    tagsEn: ['Dedicated Unit', '4 King Beds', 'Private Balcony', 'Mahjong Table', 'Floor 22'],
    amenitiesZh: [
      '4 间独立卧室均配备 1.8m 特大双人床，2 间完整卫生间',
      '高空私享揽江阳台，配备实木茶座',
      '自动静音麻将桌与宽敞家庭客厅',
      '全套洗漱备品与洗烘一体机',
    ],
    amenitiesEn: [
      '4 private bedrooms with 1.8m king beds and 2 full bathrooms',
      'High-altitude riverfront terrace with tea furniture',
      'Silent automatic mahjong table in spacious lounge',
      'Washer-dryer and complete family bath amenities',
    ],
    droneVantageZh: '22 层顶层视野，临窗阳台即可平视千架无人机编队起降，私密不挤街景。',
    droneVantageEn: '22nd floor high-altitude view; witness drone choreography from your private terrace without street crowds.',
    directPerksZh: ['官网直订立享 95 折', '尊享全家欢迎茶礼', '免费提前行李寄存'],
    directPerksEn: ['Official 5% Direct Discount', 'Family Welcome Tea Selection', 'Free Luggage Storage'],
    cancellationPolicyZh: '入住前 72 小时可免费取消；72 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 72 hours prior to check-in. Cancellations within 72 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'room_b22_02_huadengqi',
    slug: 'river-view-4-bedroom-balcony-mahjong-huadengqi',
    display_type: 'individual_room',
    pms_sku: 'BH东B22-02华灯起',
    house_type_id: 31727,
    listing_id: '1714162805-68618636',
    property_ids: [11144270],
    default_property_id: 11144270,
    nameZh: '江景阳台·4卧室大床套房·麻将桌 (华灯起)',
    nameEn: 'River View 4-Bedroom Suite with Private Balcony & Mahjong Table (Hua Deng Qi)',
    subtitleZh: '4个独立卧室1客厅2卫生间 · 4张1.8米大床 · 私享观景阳台与自动麻将机',
    subtitleEn: '4 private bedrooms, 1 living room, 2 bathrooms, 4 king beds, private balcony, and mahjong table',
    badgeZh: '独立房间 · 华灯起·22层',
    badgeEn: 'Dedicated Room · Hua Deng Qi',
    area: '152 ㎡',
    floorZh: '高空 22 层',
    floorEn: 'Floor 22',
    capacity: 8,
    bedInfoZh: '4张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '4 King Beds (1.8m × 2.0m)',
    viewZh: '两江交汇全江景 / 洪崖洞高空夜景阳台',
    viewEn: 'Two Rivers Confluence, Hongyadong Skyline Balcony',
    basePrice: 1688,
    minFloorPrice: 980,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['独立房间', '4张大床', '私享大阳台', '自动麻将桌', '高空22层'],
    tagsEn: ['Dedicated Unit', '4 King Beds', 'Private Balcony', 'Mahjong Table', 'Floor 22'],
    amenitiesZh: [
      '4 间独立卧室均配备 1.8m 特大双人床，2 间完整卫生间',
      '高空私享揽江阳台，近赏两江交汇华灯初上',
      '自动麻将桌与宽适客餐厅格局',
      '全套洗漱备品与洗烘一体机',
    ],
    amenitiesEn: [
      '4 private bedrooms with 1.8m king beds and 2 full bathrooms',
      'High-altitude private balcony facing river sunset and night illumination',
      'Automatic mahjong table in spacious living and dining area',
      'Washer-dryer and complete family bath amenities',
    ],
    droneVantageZh: '22 层顶层视野，华灯初上时居高临下观赏灯光大秀与千机飞天。',
    droneVantageEn: 'Panoramic 22nd floor perspective for sunset and nightly river light shows.',
    directPerksZh: ['官网直订立享 95 折', '尊享全家欢迎茶礼', '免费提前行李寄存'],
    directPerksEn: ['Official 5% Direct Discount', 'Family Welcome Tea Selection', 'Free Luggage Storage'],
    cancellationPolicyZh: '入住前 72 小时可免费取消；72 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 72 hours prior to check-in. Cancellations within 72 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'room_c801_xiangwu',
    slug: 'river-view-4-bedroom-balcony-mahjong-xiangwu',
    display_type: 'individual_room',
    pms_sku: 'BH东C-801香雾',
    house_type_id: 31727,
    listing_id: '1714162805-68618636',
    property_ids: [12381302],
    default_property_id: 12381302,
    nameZh: '江景阳台·4卧室大床套房·麻将桌 (香雾)',
    nameEn: 'River View 4-Bedroom Suite with Private Balcony & Mahjong Table (Xiang Wu)',
    subtitleZh: '4个独立卧室1客厅2卫生间 · 4张1.8米大床 · 私享观景阳台与自动麻将机',
    subtitleEn: '4 private bedrooms, 1 living room, 2 bathrooms, 4 king beds, private balcony, and mahjong table',
    badgeZh: '独立房间 · 香雾·8层',
    badgeEn: 'Dedicated Room · Xiang Wu',
    area: '146 ㎡',
    floorZh: '8 层',
    floorEn: 'Floor 8',
    capacity: 8,
    bedInfoZh: '4张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '4 King Beds (1.8m × 2.0m)',
    viewZh: '两江亲水江景 / 独立阳台品茗休闲',
    viewEn: 'Close-up River Vista, Private Balcony',
    basePrice: 1588,
    minFloorPrice: 920,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['独立房间', '4张大床', '私享大阳台', '自动麻将桌', '亲水江景'],
    tagsEn: ['Dedicated Unit', '4 King Beds', 'Private Balcony', 'Mahjong Table', 'Riverfront'],
    amenitiesZh: [
      '4 间独立卧室配备 4 张 1.8m 特大双人床，2 间完整卫生间',
      '私享观景阳台与自动麻将桌',
      '静音空调与洗衣机设备',
    ],
    amenitiesEn: [
      '4 private bedrooms with 4 king beds and 2 bathrooms',
      'Private riverfront balcony and automatic mahjong table',
      'Quiet air conditioning and laundry facilities',
    ],
    droneVantageZh: '近距离平视江面游船灯火，亲水感受山城烟火气。',
    droneVantageEn: 'Close-up water view with illuminated boats cruising past.',
    directPerksZh: ['官网直订立享 95 折', '尊享全家欢迎茶礼', '免费提前行李寄存'],
    directPerksEn: ['Official 5% Direct Discount', 'Family Welcome Tea Selection', 'Free Luggage Storage'],
    cancellationPolicyZh: '入住前 72 小时可免费取消；72 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 72 hours prior to check-in. Cancellations within 72 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'room_b10_2_666_zhiyu',
    slug: 'panoramic-river-view-king-suite-zhiyu',
    display_type: 'individual_room',
    pms_sku: 'BH东B10-2-666 知屿',
    house_type_id: 71446,
    listing_id: '1714162802-69081086',
    property_ids: [12316816],
    default_property_id: 12316816,
    nameZh: '全景落地窗·江景大床套房',
    nameEn: 'Panoramic River View King Suite with Floor-to-Ceiling Windows',
    subtitleZh: '通顶全景落地窗 · 临窗深泡泡池 · 专属知屿居所',
    subtitleEn: 'Full-wall panoramic glass, scenic soaking tub by the window, exclusive Zhi Yu suite',
    badgeZh: '独立房间 · 知屿·落地窗',
    badgeEn: 'Dedicated Suite · Zhi Yu',
    area: '48 ㎡',
    floorZh: '高空 10 层',
    floorEn: 'Floor 10',
    capacity: 2,
    bedInfoZh: '1张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '1 King Bed (1.8m × 2.0m)',
    viewZh: '千厮门大桥 / 嘉陵江夜色',
    viewEn: 'Qiansimen Bridge, Jialing River Night Lights',
    basePrice: 638,
    minFloorPrice: 390,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['独立房间', '全景落地窗', '临窗泡池', '千厮门大桥', '专属指定'],
    tagsEn: ['Dedicated Unit', 'Panoramic Glass', 'Soaking Tub', 'Bridge View', 'Guaranteed Room'],
    amenitiesZh: [
      '临窗定制景观泡池与精选原叶茶礼盒',
      '通顶全幅隔音落地玻璃，饱览千厮门大桥夜幕',
      '1.8m特大双人床与零压乳胶枕',
      '智能马桶与高速吹风机',
    ],
    amenitiesEn: [
      'Window-side soaking tub with organic tea amenities',
      'Floor-to-ceiling acoustic glass wall facing Qiansimen Bridge',
      '1.8m King bed with memory foam pillows',
      'Smart bidet toilet and high-velocity hair dryer',
    ],
    droneVantageZh: '大开面落地窗视野，傍晚坐在泡池边即可尽揽大桥车流灯海与天际飞星。',
    droneVantageEn: 'Expansive glass view; enjoy the evening bridge light sea from your soaking tub.',
    directPerksZh: ['官网直订立享 95 折', '免费泡汤草本浴盐包', '免费行李寄存'],
    directPerksEn: ['Official 5% Direct Discount', 'Herbal Bath Soak Kit', 'Free Luggage Storage'],
    cancellationPolicyZh: '入住前 48 小时可免费取消；48 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 48 hours prior to check-in. Cancellations within 48 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'room_b16_02_qingfeng',
    slug: 'riverfront-view-3-bedroom-suite-balcony-qingfeng',
    display_type: 'individual_room',
    pms_sku: 'BH东B16-02情风',
    house_type_id: 177692,
    listing_id: '1714162805-68618636',
    property_ids: [12381300],
    default_property_id: 12381300,
    nameZh: '正江景阳台·3卧室大床套房',
    nameEn: 'Riverfront View 3-Bedroom Suite with Private Balcony',
    subtitleZh: '3室1厅2卫3床 · 3张1.8米大床 · 正对两江交汇观景阳台 · 尊享私密大空间',
    subtitleEn: '3 bedrooms, 1 living room, 2 bathrooms, 3 king beds, front-facing river balcony',
    badgeZh: '独立房间 · 情风·3卧阳台',
    badgeEn: 'Dedicated Suite · Qing Feng',
    area: '128 ㎡',
    floorZh: '高空 16 层',
    floorEn: 'Floor 16',
    capacity: 6,
    bedInfoZh: '3张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '3 King Beds (1.8m × 2.0m)',
    viewZh: '正对两江交汇水域 / 洪崖洞高空夜景',
    viewEn: 'Front-Row Two Rivers Confluence, Hongyadong Night View',
    basePrice: 1388,
    minFloorPrice: 820,
    coverImage: '/images/retreats/baihong-room-03.jpg',
    gallery: [
      '/images/retreats/baihong-room-03.jpg',
      '/images/retreats/baihong-room-01.jpg',
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    ],
    tagsZh: ['独立房间', '3室1厅2卫', '3张大床', '正江景阳台', '亲友品质首选'],
    tagsEn: ['Dedicated Unit', '3 Beds 1 Living', '3 King Beds', 'Riverfront Balcony', 'Family Ideal'],
    amenitiesZh: [
      '3 间独立卧室均配备 1.8m 特大双人床，2 间完整卫生间',
      '正对两江交汇宽幅揽江阳台与实木茶座',
      '中央空调、全自动洗衣机与多家庭备品',
    ],
    amenitiesEn: [
      '3 private bedrooms, each with 1.8m king beds, and 2 full bathrooms',
      'Front-facing river balcony with solid wood tea station',
      'Central AC, automatic washer, and comprehensive amenities',
    ],
    droneVantageZh: '16 层黄金观景高度，正对朝天门天幕与两江汇流空域。',
    droneVantageEn: 'Prime 16th-floor height facing the water convergence and aerial show zones.',
    directPerksZh: ['官网直订立享 95 折', '专属东方迎宾欢迎茶礼', '免费行李寄存'],
    directPerksEn: ['Official 5% Direct Discount', 'Complimentary Welcome Tea Gift', 'Free Luggage Storage'],
    cancellationPolicyZh: '入住前 48 小时可免费取消；48 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 48 hours prior to check-in. Cancellations within 48 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'room_b7_2_whole_suite',
    slug: 'hongyadong-panoramic-3-bedroom-apartment-theater',
    display_type: 'individual_room',
    pms_sku: 'BH东B7-2 整套',
    house_type_id: 177692,
    listing_id: '1714162805-68618636',
    property_ids: [12653073],
    default_property_id: 12653073,
    nameZh: '洪崖洞云端全江景·3卧室整套·巨幕影院',
    nameEn: 'Hongyadong Panoramic River View 3-Bedroom Apartment with Home Theater',
    subtitleZh: '3室1厅3床整套格局 · 3张1.8米大床 · 巨幕影院高清投屏 · 云端全江景',
    subtitleEn: 'Entire 3-bedroom apartment with 3 king beds, home cinema projector, panoramic riverfront views',
    badgeZh: '独立房间 · 3卧整套·影院',
    badgeEn: 'Dedicated Suite · Home Theater',
    area: '125 ㎡',
    floorZh: '高空 7 层',
    floorEn: 'Floor 7',
    capacity: 6,
    bedInfoZh: '3张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '3 King Beds (1.8m × 2.0m)',
    viewZh: '两江交汇全江景 / 城市天际线',
    viewEn: 'Two Rivers Confluence, Cyberpunk City Skyline',
    basePrice: 1388,
    minFloorPrice: 820,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['独立房间', '3室整套包栋', '3张大床', '巨幕影院投屏', '云端全江景'],
    tagsEn: ['Dedicated Unit', 'Entire 3-Bed Flat', '3 King Beds', 'Cinema Projector', 'River Panorama'],
    amenitiesZh: [
      '3 间独立卧室配备 3 张 1.8m 特大双人床',
      '客厅配备百寸高清巨幕影音投影仪与工夫茶台',
      '全自动洗衣烘干机与厨房冰箱',
    ],
    amenitiesEn: [
      '3 private bedrooms with three 1.8m king beds',
      'Spacious lounge with 100-inch cinema projector and Kung Fu tea table',
      'Washer-dryer and refrigerator facilities',
    ],
    droneVantageZh: '近邻两江江岸，夜间在客厅关灯即可尊享巨幕观影与窗外江景交织的沉浸体验。',
    droneVantageEn: 'Immersive home theater experience with glowing river waters outside the window.',
    directPerksZh: ['官网直订立享 95 折', '全家出行专属茶礼', '免费提前行李寄存'],
    directPerksEn: ['Official 5% Direct Discount', 'Family Tea Gift', 'Free Luggage Storage'],
    cancellationPolicyZh: '入住前 48 小时可免费取消；48 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 48 hours prior to check-in. Cancellations within 48 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
  {
    room_key: 'room_b21_02_whole_suite',
    slug: 'hongyadong-river-view-4-bedroom-apartment-b2102',
    display_type: 'individual_room',
    pms_sku: 'BH东B21-02 整套',
    house_type_id: 191968,
    listing_id: '1714162805-68618636',
    property_ids: [12489988],
    default_property_id: 12489988,
    nameZh: '洪崖洞江景·4卧室整套大床公寓',
    nameEn: 'Hongyadong River View 4-Bedroom Apartment',
    subtitleZh: '四室0厅3卫四床整套格局 · 4张1.8米大床 · 洪崖洞高空一线江景',
    subtitleEn: 'Entire 4-bedroom apartment with 4 king beds, 3 bathrooms, front-row Hongyadong river vista',
    badgeZh: '独立房间 · 4卧整套大床',
    badgeEn: 'Dedicated Apartment · 4 King Beds',
    area: '160 ㎡',
    floorZh: '高空 21 层',
    floorEn: 'Floor 21',
    capacity: 8,
    bedInfoZh: '4张特大双人床 (1.8m × 2.0m)',
    bedInfoEn: '4 King Beds (1.8m × 2.0m)',
    viewZh: '两江汇流全景 / 洪崖洞高空灯火',
    viewEn: 'River Confluence, Hongyadong Lights',
    basePrice: 1688,
    minFloorPrice: 980,
    coverImage: 'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
    gallery: [
      'https://yojqi.com/wp-content/uploads/2026/05/baihong-hongyadong-view-5.jpg',
      'https://yojqi.com/wp-content/uploads/2026/03/baihong-hongyadong-view.jpg',
      '/images/retreats/baihong-drone-night.jpg',
    ],
    tagsZh: ['独立房间', '4室整套', '4张大床', '3独立卫浴', '高空21层一线江景'],
    tagsEn: ['Dedicated Unit', 'Entire 4-Bed Flat', '4 King Beds', '3 Bathrooms', '21st Floor River View'],
    amenitiesZh: [
      '四室 3 卫独立整套，4 张 1.8m 特大双人床满足 8 位宾客居住',
      '高空 21 层开阔视野，尽揽两江汇流与城市灯海',
      '干湿分离卫浴空间、全自动洗衣机与高品质备品',
    ],
    amenitiesEn: [
      'Entire apartment with 4 private bedrooms, 4 king beds, and 3 full bathrooms for 8 guests',
      'Expansive 21st-floor panoramic views over river convergence and city night lights',
      'Full bathrooms, automatic washer, and comprehensive amenities',
    ],
    droneVantageZh: '21 层高空一线视野，无人机航线与两江夜景尽收眼底。',
    droneVantageEn: '21st floor front-row line of sight over the nightly drone flights and river reflections.',
    directPerksZh: ['官网直订立享 95 折', '尊享全家欢迎茶礼', '免费提前行李寄存', 'VIP管家服务'],
    directPerksEn: ['Official 5% Direct Discount', 'Family Welcome Tea Selection', 'Free Luggage Storage', 'VIP Butler'],
    cancellationPolicyZh: '入住前 72 小时可免费取消；72 小时内取消扣除首晚房费。',
    cancellationPolicyEn: 'Free cancellation up to 72 hours prior to check-in. Cancellations within 72 hours incur first night charge.',
    checkInTime: '15:00',
    checkOutTime: '12:00',
  },
];

export function getRoomCatalog(): RetreatRoomType[] {
  return RETREAT_ROOM_CATALOG;
}

export function getRoomBySlug(slug: string): RetreatRoomType | undefined {
  return RETREAT_ROOM_CATALOG.find((r) => r.slug === slug || r.room_key === slug);
}

export function getRoomByKey(roomKey: string): RetreatRoomType | undefined {
  return RETREAT_ROOM_CATALOG.find((r) => r.room_key === roomKey);
}

export function getRoomTypesOnly(): RetreatRoomType[] {
  return RETREAT_ROOM_CATALOG.filter((r) => r.display_type === 'room_type');
}

export function getIndividualRoomsOnly(): RetreatRoomType[] {
  return RETREAT_ROOM_CATALOG.filter((r) => r.display_type === 'individual_room');
}
